import Head from 'next/head';
import styled from 'styled-components';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>TODO Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>{children}</Container>
    </>
  );
};

const Container = styled.div``;

export default Layout;
