import Head from 'next/head';
import styled from 'styled-components';
import Footer from './Footer';
import Header from './Header';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>TODO Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Header />
        <BodyContainer>{children}</BodyContainer>
        <Footer />
      </Container>
    </>
  );
};

const Container = styled.div``;

const BodyContainer = styled.div``;

export default Layout;


const WW = styled.input.attrs({ type: 'checkbox' })`

`